travis:
  secure:
    BINSTAR_TOKEN: HNuJpEDo2OYw9WIxqBztSP3ThaWfA9Su8MlXh/OjXPtqbisFiey7jF/A+t6zujj7kjj5VG9QPKp5oew+TUgIPRWaTZVE3EHyVFEUJsmyGlPHmCjYtH5wRMDn7aaVhLnYhd0e3zxUQORWlpVOJ34NfgQVhPnIj6l2RMUcUk6eovnW7egbMw6vwgxGsjW/5RE2A20Q6ryEvbca3wcyTQ8WcqBVY8Xtb3ZkqFmvPiqCieb/VoVswGyzxwLkQWvMYaeDc4oJ6K6l+O4sCXajOHsONVP3fVJ3NtSr1wdn93exCBLoGKKCAMbxZePRcAugyFjVDkGtmOkCzHJCAp+a6AvVE7UYp85PVXnW+GoCvDaOiL8WCPS159wRA1nZcFlyxjT8l3t8auxAsYqFN5GusOS2PG+BWZU2TxIFsYrtM5IaDowxcjcB74FNWAZ7fWQapWTPPIs67fyT6K58kgRitPKughVLFXxKOBRKiuEnihtdZoBvprmlJms/fG4YMBG645ErOZJNjSeCL6XlcgHqK3XwSCXj12MhoOGC570ofvzke3yUOXqhKGe0By282SZV264zrIoKiEElwVBdDOClqQ6zjGaDwA8NEGGUDNgUpPu/cBNKPT94X6I6SA9lIqH+fUDTaAO3wUZQGzBLSL8iaeVmNvWK0NduzKmBCFgekyaxYWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
